baseURL: https://wanyu-wang-website.netlify.app/
languageCode: en-us
title: Portfolio website for Wanyu Wang
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Hola!
      This is Winnie~
    title: Hi, my name is Wanyu Wang. Welcome to my website!
  blog: {}
  contact:
    address:
      - city: London, ST 00000
        country: UK
        street: Sussex Place
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: wwang.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (000) 000-0000 x1234
        title: Phone
  custom_css: []
  custom_js: []
  description: I am Wanyu Wang from London Business School.
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: London Business School
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: https://www.twitter.com
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/profile.php?id=100023920160600&sk=about
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/bonnieshark_w/
      - icon: fa-github
        label: GitHub
        url: https://github.com/wanyu-wang/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/皖豫-王-511825219/
  image: ''
  name: Wanyu Wang
  navigation:
    button1:
      - name: Get Started
        url: blogs
#    button2:
#      - name: Log In
#        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Look at me!
        title: My Photos
        url: blogs/aliquam
      - image: pic02.jpg
        subtitle: This is me.
        title: My CV
        url: blogs/tempus
      - image: pic03.jpg
        subtitle: See my work
        title: My Work
        url: blogs/magna
      - image: pic04.jpg
        subtitle: Know about me
        title: My Biography
        url: blogs/ipsum
#      - image: pic05.jpg
#        subtitle: Ipsum Dolor Sit Amet
#        title: Consequat
#        url: blogs/ipsum
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Hi welcome to Winnie's blog.
      \n    You can see my life here. 
      \n    Enjoy yourself exploring my website."" ""
    title: Winnie's Blog
    url: blogs